### ISSUE TITLE
Get-PowerBIActivityEvent Returning [] - Empty Results

### ISSUE THREAD

**Issue by pugliathomas** [microsoft/powerbi-powershell#299]
Ever since this Tuesday (June 1st, 2021), the normal script I run on a weekly basis to pull Activity data from Power BI started returning null values. I normally export CSV, and if I am pulling one day or looping multiple days I cannot get any data. 

I updated all PowerBIMgmt modules and imported them, but no luck. 

I tried in both PowerShell ISE and Visual Studio Code.

![image](https://user-images.githubusercontent.com/6196804/120736253-90a63800-c4b1-11eb-8c10-f4c18bec293d.png)

**Comment by pugliathomas** [comment]
> It's doesn't seem to be something related to the cmdlet specifically. Are you able to get response directly when calling API directly? https://docs.microsoft.com/en-us/rest/api/power-bi/admin/getactivityevents

No go. Tried even in the docs.microsoft.com REST API Try It window:

![image](https://user-images.githubusercontent.com/6196804/121934460-f04fdf00-cd0c-11eb-9f8c-4ef1e751c2d1.png)

**Comment by CattieCat** [comment]
What you get back is by design from try it. ActivityEvents response is paginated by hour, if you keep calling with continuationToken value, you'll get response from next hour. You get complete results by repeat this until there's no continuationToken exists in response. 

Get-PowerBIActivityEvent will do above steps for you and I hope you can try again from this cmdlet and take a fiddler trace, see if there's any call failed with api.powerbi.com.

**Comment by pugliathomas** [comment]
It seems now that there was only a lapse between May 26th - and May 31st with the [] results. I am now able to collect data june 1st and forward.
